feat: tweakwise header source
EmicoEcommerce/Magento2Tweakwise pull request #224
Opened 2024-10-03 14:44 UTC by ah-net

Add TWN-source header to request.

See https://docs.tweakwise.com/docs/request-source

2024-10-11 07:15 UTC, jansentjeu requested changes

2024-10-11 07:15 UTC, jansentjeu commented on Model/Config.php
Fix lint issue in this file

2024-10-16 08:57 UTC, ah-net commented on Model/Config.php
Lint issue is fixed

2024-10-16 09:09 UTC, jansentjeu approved these changes

2024-10-16 09:15 UTC, merged