Feat: tw analytics
EmicoEcommerce/Magento2Tweakwise pull request #229
Opened 2024-11-20 13:47 UTC by ah-net

Features: 

- Added personalised search result
- Added setting to send productview/search and purchase requests to analytics api. With this setting enabled an separate javascript tracking script is not needed anymore for personal merchandising to work.

2024-12-10 10:36 UTC, ah-net commented
@jansentjeu Modified it so that the tw request is handled by php. And moved the search personalisation to an diffrent pull request

2024-12-11 07:51 UTC, jansentjeu requested changes

2024-12-11 07:51 UTC, jansentjeu commented on Block/Catalog/PersonalMerchandisingAnalytics.php
> +    public function __construct(
Add phpdoc to all functions

2024-12-11 07:51 UTC, jansentjeu commented on Block/Catalog/PersonalMerchandisingAnalytics.php
Use a `ViewModel` if the class is only used to serve data. See https://m.academy/articles/magento-block-class-vs-view-model/

2024-12-11 07:51 UTC, jansentjeu commented on Model/Client.php
> +    protected function createPostRequest(Request $tweakwiseRequest): HttpRequest
Add phpdoc to functions

2024-12-11 07:51 UTC, jansentjeu commented on Model/Client/Request.php
> +    public function setParameterArray(string $parameter, array $value)
Add phpdoc

2024-12-11 07:51 UTC, jansentjeu commented on etc/frontend/di.xml
> +    <virtualType name="Tweakwise\Magento2Tweakwise\Block\SearchResult\ListProduct"
Personal merchandising code

2024-12-11 07:51 UTC, jansentjeu commented on view/frontend/web/js/product-page.js
product-page.js and search-page.js look very similar. Can you create 1 generic file for this that you can use for both cases?

2024-12-13 08:30 UTC, ah-net commented on Block/Catalog/PersonalMerchandisingAnalytics.php
> +    public function __construct(
Changes implemented

2024-12-13 08:30 UTC, ah-net commented on Block/Catalog/PersonalMerchandisingAnalytics.php
Changes implemented

2024-12-13 08:30 UTC, ah-net commented on Model/Client/Request.php
> +    public function setParameterArray(string $parameter, array $value)
Changes implemented

2024-12-13 08:36 UTC, ah-net commented on Model/Client.php
> +    protected function createPostRequest(Request $tweakwiseRequest): HttpRequest
Changes implemented

2024-12-13 08:36 UTC, ah-net commented on view/frontend/web/js/product-page.js
Changes implemented

2024-12-13 08:39 UTC, ah-net commented on etc/frontend/di.xml
> +    <virtualType name="Tweakwise\Magento2Tweakwise\Block\SearchResult\ListProduct"
Changes implemented

2024-12-16 12:09 UTC, jansentjeu requested changes

2024-12-16 12:09 UTC, jansentjeu commented on Controller/Ajax/Analytics.php
> +     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\Result\Json|\Magento\Framework\Controller\ResultInterface
Add classes as `use` statement

2024-12-16 12:09 UTC, jansentjeu commented on Model/Client.php
> +        $uri = new Uri($tweakwiseRequest->getApiUrl() . '/' . $path);
Can we use the URL builder here?

2024-12-16 12:09 UTC, jansentjeu commented on view/frontend/templates/product/page.phtml
We can make it more generic. If we add an argument like `analyticsType` in the layout, than we can check this in the phtml to add the product key value when type is `product` and search query value when type is `search`.
Example:

```
<?php

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */
/** @var  Escaper $escaper */

/** @var \Tweakwise\Magento2Tweakwise\ViewModel\PersonalMerchandisingAnalytics $viewModel */
$viewModel = $block->getData('viewModel');
$analyticsType = $block->getData('analyticsType');
$value = $analyticsType === 'product' ? $viewModel->getProductKey() : $viewModel->getSearchQuery();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Tweakwise_Magento2Tweakwise/js/analytics": {
              "value": "<?= $escaper->escapeHtmlAttr($value); ?>",
              "type": "<?= $analyticsType; ?>"
        }
    }
}
</script>
<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_Magento2Tweakwise::js/analytics.js')); ?>"></script>
```

2024-12-17 09:40 UTC, ah-net commented on Controller/Ajax/Analytics.php
> +     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\Result\Json|\Magento\Framework\Controller\ResultInterface
Implemented changes

2024-12-17 09:40 UTC, ah-net commented on Model/Client.php
> +        $uri = new Uri($tweakwiseRequest->getApiUrl() . '/' . $path);
Implemented changes

2024-12-17 09:41 UTC, ah-net commented on view/frontend/templates/product/page.phtml
Implemented changes

2024-12-17 12:47 UTC, jansentjeu requested changes

2024-12-17 12:47 UTC, jansentjeu commented on Model/Client.php
> +            $url   = sprintf('%s?%s', $url, $query);
Space

2024-12-17 12:53 UTC, ah-net commented on Model/Client.php
> +            $url   = sprintf('%s?%s', $url, $query);
Removed it

2024-12-17 12:55 UTC, jansentjeu approved these changes

2024-12-17 12:57 UTC, merged