Fixed fallback
EmicoEcommerce/Magento2Tweakwise pull request #70
Opened 2023-06-27 14:45 UTC by ah-net

Fixes #51

2023-06-28 08:43 UTC, dz-optimizers requested changes
In Hyva nog niet altijd goed. Zie issue comment.

2023-07-04 07:32 UTC, dz-optimizers approved these changes

2023-08-08 06:32 UTC, jspoe commented
Do you have a roadmap / milestone when this PR will be released?

2023-08-22 12:48 UTC, ah-net commented
@jspoe I expect this or next week.

I've been on holliday the past few weeks. I need to test this with the hyva theme and make changes there if needed.

2023-08-23 07:43 UTC, merged